[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@account-abstraction/=lib/account-abstraction/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@foundry-era-contracts/contracts/=lib/foundry-era-contracts/src/system-contracts/contracts/",
]

via_ir = true
optimizer = true
optimizer_runs = 200

[profile.zksync]
zksync = true
src = 'src/Zksync'
test = 'test/Zksync'
script = 'script/Zksync'

[profile.zksync.zksolc]
is_system = true
force_evmla = false
optimizer_enabled = true
optimizer_mode = "3"